src/MAM/RHBundle/Entity/CV.php
<?php

namespace MAM\RHBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * CV
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="MAM\RHBundle\Entity\CVRepository")
 * @ORM\HasLifecycleCallbacks
 */
class CV
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255,nullable=true)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255,nullable=true)
     */
    private $alt;

    private $file;

    private $tempFilename;


    public function setFile(UploadedFile $file)
    {
        $this->file = $file;
        if (null !== $this->url) {
            $this->tempFilename = $this->url;
            $this->url = null;
            $this->alt = null;
        }
    }
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null === $this->file) {
            return;
        }
        $this->url = $this->file->guessExtension();
        $this->alt = $this->file->getClientOriginalName();
    }
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->file) {
            return;
        }
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }
        $this->file->move($this->getUploadRootDir(), $this->id.'.'.$this->url);
    }
    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if (file_exists($this->tempFilename)) {
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        return 'uploads/cv';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    public function getWebPath()
    {
        return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }

    public function getFile()
    {
        return $this->file;
    }
}

src/MAM/RHBundle/Controller/RHController.php
<?php

namespace MAM\RHBundle\Controller;

use MAM\RHBundle\Entity\News;
use MAM\RHBundle\Form\NewsType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Security\Core\SecurityContext;

use MAM\UserBundle\Entity\User;

use FOS\UserBundle\Mailer\TwigSwiftMailer;

use MAM\RHBundle\Entity\ResponsableRH;
use MAM\RHBundle\Entity\Employenormal;
use MAM\RHBundle\Entity\Attestation;
use MAM\RHBundle\Entity\Employe;
use MAM\RHBundle\Entity\ChefDepartement;
use MAM\RHBundle\Entity\Departement;

use MAM\RHBundle\Entity\Offre;
use MAM\RHBundle\Entity\Stagiaire;

use MAM\RHBundle\Form\EmployeType;
use MAM\RHBundle\Form\OffreType;
use MAM\RHBundle\Form\StagiaireType;


class RHController extends Controller
{
    public function AcceuilAction()
    {
        $id = $this->getUser()->getEmploye()->getId();
        $entities=$this->getDoctrine()
            ->getManager()
            ->getRepository('MAMRHBundle:News')
            ->findAll();
        //var_dump($entities);

        $em = $this->getDoctrine()->getManager();

        $demandenonv = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandenonV($this->getUser());

        $demandev = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandeV($this->getUser());

        if ($this->get('security.context')->isGranted('ROLE_EMP')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojet($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_PROJET')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetchef($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_DEP')){
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetdep($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_RH')){
            $nbrprojet[0][1] = 0;
        }

        if ($this->get('security.context')->isGranted('ROLE_RH') or $this->get('security.context')->isGranted('ROLE_CHEF_DEP')){
            $nbrstagiaire = $em->getRepository('MAMRHBundle:Stagiaire')
                ->getnbrprojetrh();
        }
        else{
            $nbrstagiaire = $em->getRepository('MAMRHBundle:Stagiaire')
                ->getnbrprojet($this->getUser());
        }

        return $this->render('MAMRHBundle:RH:Acceuil.html.twig',array('entities' => $entities,
            'demandenonv'=>$demandenonv[0][1],
            'demandev'=>$demandev[0][1],
            'nbrprojet'=>$nbrprojet[0][1],
            'nbrstagiaire'=>$nbrstagiaire[0][1],'id' => $id));
    }
    public function ajoutemployeAction()
    {
        $employe = new Employenormal();
        $form = $this->createForm(new EmployeType(),$employe);
        $request = $this->get('request');

        $em = $this->getDoctrine()->getManager();

        $demandenonv = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandenonV($this->getUser());

        $demandev = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandeV($this->getUser());

        if ($this->get('security.context')->isGranted('ROLE_EMP')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojet($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_PROJET')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetchef($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_DEP')){
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetdep($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_RH')){
            $nbrprojet[0][1] = 0;
        }

        if ($this->get('security.context')->isGranted('ROLE_RH') or $this->get('security.context')->isGranted('ROLE_CHEF_DEP')){
            $nbrstagiaire = $em->getRepository('MAMRHBundle:Stagiaire')
                ->getnbrprojetrh();
        }
        else{
            $nbrstagiaire = $em->getRepository('MAMRHBundle:Stagiaire')
                ->getnbrprojet($this->getUser());
        }

        if ($request->getMethod() == 'POST') {
            $form->submit($request);
            if ($form->isValid()) {
                $tokenGenerator = $this->container->get('fos_user.util.token_generator');
                $userManager = $this->container->get('fos_user.user_manager');
                $user = $userManager->createUser();

                $dep = $this->getDoctrine()
                    ->getManager()
                    ->getRepository('MAMRHBundle:Departement')
                    ->find($employe->getDepartement()->getId());
                //if($dep instanceof Departement) var_dump($dep);

                $dep->addEmploye($employe);
                $user->setRoles(array('ROLE_EMP'));
                $employe->setMatricule(substr($tokenGenerator->generateToken(), 0, 6));
                $employe->setDateEmbauche(new \Datetime());
                $employe->setBye(false);
                $user->setEmail($employe->getEmail());
                $user->setUsername($employe->getEmail());
                $passhelp=substr($tokenGenerator->generateToken(), 0, 10);
                $user->setPlainPassword($passhelp);
                $user->setEnabled(true);
                $user->setEmploye($employe);
                $employe->setUser($user);
                //var_dump($employe);

                $em->persist($employe);
                $em->persist($user);


                if($this->confirmation($user,$passhelp)) $em->flush();
                else throw new AccessDeniedHttpException('Email non envoyer');


                $this->get('session')->getFlashBag()->add('info', 'Employé bien ajouté');
                //var_dump($user);

                return $this->redirect($this->generateUrl('mamrh_ajoutemploye'));
            }
        }
        $id = $this->getUser()->getEmploye()->getId();
        return $this->render('MAMRHBundle:RH:AjoutEmploye.html.twig',array('form' => $form->createView(),
            'demandenonv'=>$demandenonv[0][1],
            'demandev'=>$demandev[0][1],
            'nbrprojet'=>$nbrprojet[0][1],
            'nbrstagiaire'=>$nbrstagiaire[0][1],'id'=>$id));
    }

    public function ajoutoffreAction()
    {
        $id = $this->getUser()->getEmploye()->getId();
        $offre = new Offre();
        $form = $this->createForm(new OffreType(), $offre);
        $request = $this->get('request');


        $em = $this->getDoctrine()->getManager();

        $demandenonv = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandenonV($this->getUser());

        $demandev = $em->getRepository('MAMRHBundle:Attestation')
            ->getnbrdemandeV($this->getUser());

        if ($this->get('security.context')->isGranted('ROLE_EMP')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojet($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_PROJET')) {
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetchef($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_CHEF_DEP')){
            $nbrprojet = $em->getRepository('MAMRHBundle:Projet')
                ->getnbrprojetdep($this->getUser());
        }
        if ($this->get('security.context')->isGranted('ROLE_RH')){
            $nbrprojet[0][1] = 0;
        }

        if ($this->get('security.context')->isGranted('ROLE_RH') or $this->get('security.context')->isGranted('ROLE_CHEF_DEP')){
            $nbrstagiaire = $em->getRepository('MAMRHBundle:Stagiaire')
                ->getnbrprojetrh();
        }
        else{
            $nbrstagiaire = $em->getRepository('MAMRHBundle:Stagiaire')
                ->getnbrprojet($this->getUser());
        }

        if ($request->getMethod() == 'POST') {
            $form->submit($request);
            if ($form->isValid()) {

                $rh = $em->getRepository('MAMRHBundle:ResponsableRH')->find($this->getUser());
                //var_dump($rh);
                $offre->setResponsableRH($rh);

                $em->persist($offre);
                $em->flush();
                $this->get('session')->getFlashBag()->add('info', 'Offre bien ajouté');


                return $this->redirect($this->generateUrl('mamrh_Listoffre'));
            }
        }
        return $this->render('MAMRHBundle:RH:AjoutOffre.html.twig',array('form' => $form->createView(),
            'demandenonv'=>$demandenonv[0][1],
            'demandev'=>$demandev[0][1],
            'nbrprojet'=>$nbrprojet[0][1],
            'nbrstagiaire'=>$nbrstagiaire[0][1],'id'=>$id));
    }
    public function getemployenormalAction()
    {
        $em = $this->getDoctrine()->getManager();
        $entities=$this->getDoctrine()
                ->getManager()
                ->getRepository('MAMRHBundle:Employe')
                ->getemployenormal();
        $i = 0;
        //var_dump($entities);
        $e = array();
        foreach($entities as $en){
            //$query = "SELECT dtype FROM employe WHERE id=".$e->getId();
            //$dtype[$i] = $em->getConnection()->exec($query);

            $connection = $em->getConnection();
            $statement = $connection->prepare("SELECT dtype FROM employe WHERE id = :id");
            $statement->bindValue('id', $en->getId());
            $statement->execute();
            $dtype[$i] = $statement->fetchAll();

            //array_push($e,$dtype[$i],$en);

            $i++;
        }
        //var_dump($e);
        //var_dump($dtype[0][0]['dtype']);

src/MAM/RHBundle/Resources/views/RH/Acceuil.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Tableau de Bord{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}

{% block corps %}

<div class="col-lg-8">

<div class="panel panel-default">
    <div class="panel-heading">
        <i class="fa fa-clock-o fa-fw"></i> Nouveautés
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <ul class="timeline">
            {% set i = 0 %}
            {% for i in 1..(entities|length)%}
                {% if(i%2 != 0) %}
            <li>
                <div class="timeline-badge"><i class="fa fa-check"></i>
                </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="timeline-title">{{ entities[i-1].libelle }}</h4>
                        <p><small class="text-muted"><i class="fa fa-clock-o"></i>{{ entities[i-1].CreatedAt|date('d/m/Y H:i:s') }}</small>
                        </p>
                    </div>
                    <div class="timeline-body">
                        <p>{{ entities[i-1].discription }}</p>
                    </div>
                </div>
            </li>
                {% endif %}
                {% set i = i+1 %}
                {% if(i <= (entities|length) and i%2 ==0) %}
            <li class="timeline-inverted">
                <div class="timeline-badge warning"><i class="fa fa-credit-card"></i>
                </div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4 class="timeline-title">{{ entities[i-1].libelle }}</h4>
                        <p><small class="text-muted"><i class="fa fa-clock-o"></i>{{ entities[i-1].CreatedAt|date('d/m/Y H:i:s') }}</small>
                        </p>
                    </div>
                    <div class="timeline-body">
                        <p>{{ entities[i-1].discription }}</p>
                    </div>
                </div>
            </li>
                {% endif %}
                {% set i = i+1 %}
            {% endfor %}
        </ul>
</div>
</div>

</div>
{% endblock %}

src/MAM/RHBundle/Resources/views/RH/AjoutEmploye.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Ajouter un Employe{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}

{% block corps %}
<div class="col-lg-8">
   <form method="post" {{form_enctype(form) }}>
       <div class="row">
           <div class="col-lg-6">
                  <div class="panel panel-primary">
                      <div class="panel-heading">
                          <i class="fa fa-unlock"></i>
                          &nbsp;&nbsp;Informations générales
                      </div>
                      <div class="panel-body">
                          {{ form_errors(form) }}
                          <div class="form-group">

                                    <label>{{ form_label(form.Nom, "Nom ") }}</label>
                                    <div class="form-control">
                                        {{ form_widget(form.Nom) }}
                                    </div>
                          </div>
                          <div class="form-group">

                                    <label>{{ form_label(form.Prenom, "Prenom ") }}</label>
                                    <div class="form-control">
                                        {{ form_widget(form.Prenom) }}
                                    </div>
                          </div>
                          <div class="form-group">

                                    <label>{{ form_label(form.CIN, "CIN ") }}</label>
                                    <div class="form-control">
                                        {{ form_widget(form.CIN) }}
                                    </div>

                          </div>
                          <div class="form-group">
                                    <label>{{ form_label(form.Adresse, "Adresse ") }}</label>

                                        {{ form_widget(form.Adresse) }}
                          </div>
                          <div class="form-group">
                                    <label>{{ form_label(form.email, "email ") }}</label>
                                    <div class="form-control">
                                        {{ form_widget(form.email) }}
                                    </div>
                                </div>
                          <div class="form-group">
                              <label>{{ form_label(form.Tel, "Tel ") }}</label>
                              <div class="form-control">
                                  {{ form_widget(form.Tel) }}
                              </div>
                          </div>
                          <div class="form-group">
                              <label>{{ form_label(form.departement, "Departement") }}</label>
                              <div class="form-control">
                                  {{ form_widget(form.departement) }}
                              </div>
                          </div>
                          <div class="form-group">
                              <label>{{ form_label(form.Diplome, "Dérnier diplome") }}</label>
                              <div class="form-control">
                                  {{ form_widget(form.Diplome) }}
                              </div>
                          </div>
                          <div class="form-group">
                              {{ form_widget(form.image) }}
                          </div>
                      </div>
                  </div>
                  </div>
           <div class="col-lg-6">
                  <div class="panel panel-primary">
                      <div class="panel-heading">
                          <i class="fa fa-lock"></i>
                          &nbsp;&nbsp;Informations personnelles
                      </div>
                      <div class="panel-body">
                          <div class="form-group">
                              <label>{{ form_label(form.Num_comptbanq, "Numéro de compte ") }}</label>
                          <div class="form-control">
                              {{ form_widget(form.Num_comptbanq) }}
                          </div>
                          </div>
                          <div class="form-group">
                              <label>{{ form_label(form.Cnss, "CNSS ") }}</label>
                          <div class="form-control">
                              {{ form_widget(form.Cnss) }}
                          </div>
                          </div>
                          <div class="form-group">
                              <label>{{ form_label(form.Cimr, "CIMR ") }}</label>
                          <div class="form-control">
                              {{ form_widget(form.Cimr) }}
                          </div>
                          </div>
                          <div class="form-group">
                              <label>{{ form_label(form.Type_contrat, "Type de contrat ") }}</label>
                              <div class="form-control">
                                  {{ form_widget(form.Type_contrat) }}
                              </div>
                          </div>
                          <div class="form-group">
                              <label>{{ form_label(form.Formation, "Formation") }}</label>
                              <div class="form-control">
                                  {{ form_widget(form.Formation) }}
                              </div>
                          </div>
                          <div class="form-group">
                              <label>{{ form_label(form.Fonction, "Fonction") }}</label>
                              <div class="form-control">
                                  {{ form_widget(form.Fonction) }}
                              </div>
                          </div>
                          <div class="form-group">
                              <label>{{ form_label(form.Specialite, "Spécialite") }}</label>
                              <div class="form-control">
                                  {{ form_widget(form.Specialite) }}
                              </div>
                          </div>

                          <div class="form-group">
                              <label>{{ form_label(form.Salaire, "Salaire") }}</label>
                              <div class="form-control">
                                  {{ form_widget(form.Salaire) }}
                              </div>
                          </div>
                          <div class="form-group">
                              {{ form_widget(form.cv) }}
                          </div>
                      </div>
                  </div>
              </div>
       </div>
       <div class="row">
               <div class="col-lg-12">
               <button type="submit" class="btn btn-outline  btn-primary">Envoyer</button>
               <button type="reset" class="btn btn-outline  btn-primary">Renitialiser</button>
               </div>
       </div>
       {{ form_rest(form) }}
       </form>
</div>

{% endblock %}

src/MAM/RHBundle/Resources/views/RH/AjoutOffre.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Ajouter une Offre{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}

{% block corps %}
    <div class="col-lg-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <i class="fa fa-edit"></i>
                &nbsp;Formulaire d'ajout d'un offre
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-8">
                        <div >
                            <form method="post" {{ form_enctype(form) }}>
                                {{ form_errors(form) }}
                                <div class="form-group">
                                    <label>{{ form_label(form.typeoffre, "Le type de L'offre") }}</label>
                                    <div class="form-control">
                                        {{ form_widget(form.typeoffre) }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>{{ form_label(form.libelle, "Libellé de l'offre ") }}</label>
                                    <div class="form-control">
                                        {{ form_widget(form.libelle) }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>{{ form_label(form.descriptif, "Description ") }}</label>

                                        {{ form_widget(form.descriptif) }}

                                </div>
                                <button type="submit" class="btn btn-outline btn-primary">Envoyer</button>
                                {{ form_rest(form) }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/MAM/RHBundle/Resources/views/RH/Ajoutnews.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Ajouter une Offre{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}

{% block corps %}
    <div class="col-lg-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <i class="fa fa-edit"></i>
                &nbsp;Formulaire d'ajout d'un offre
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-8">
                        <div >
                            <form method="post" {{ form_enctype(form) }}>
                                {{ form_errors(form) }}

                                <div class="form-group">
                                    <label>{{ form_label(form.Libelle, "Titre") }}</label>
                                    <div class="form-control">
                                        {{ form_widget(form.Libelle) }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>{{ form_label(form.discription, "Description ") }}</label>

                                        {{ form_widget(form.discription) }}

                                </div>
                                <button type="submit" class="btn btn-outline btn-primary">Envoyer</button>
                                {{ form_rest(form) }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/MAM/RHBundle/Resources/views/RH/Candidat.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Postulation{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}


{% block corps %}
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <i class="fa fa-th-list"></i>
                Tableau des Postulations
            </div>
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                        <tr>
                            <th>CIN</th>
                            <th>Nom</th>
                            <th>Prénom</th>
                            <th>Email</th>
                            <th>Spécialité</th>
                            <th>Diplome</th>
                            <th>Télé</th>
                            <th>CV</th>
                        </tr>
                        </thead>


                        <tbody>

                            <tr class="odd gradeX">
                                <td>{{ entities.CIN }}</td>
                                <td>{{ entities.Nom }}</td>
                                <td>{{ entities.Prenom }}</td>
                                <td>{{ entities.Email }}</td>
                                <td>{{ entities.Specialite }}</td>
                                <td>{{ entities.Diplome }}</td>
                                <td>{{ entities.Tel }}</td>
                                <td>{{ asset(entities.cv.webPath) }}</td>
                            </tr>

                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block panel %}
{% endblock %}

src/MAM/RHBundle/Resources/views/RH/archivestagiaire.html.twig
{% extends "::base.html.twig" %}
{% block sstitle %}Liste des stagiaires{% endblock %}

{% block projet %}{{ nbrprojet }}{% endblock %}
{% block demnov %}{{ demandev }}{% endblock %}
{% block stagiaire %}{{ nbrstagiaire }}{% endblock %}
{% block demnonv %}{{ demandenonv }}{% endblock %}

{% block corps %}
<div class="col-lg-12">
    <div class="panel panel-primary">
       <div class="panel-heading">
           <i class="fa fa-list-alt"></i>
           Tableau des stagiaires
       </div>
       <div class="panel-body">
           <div class="dataTable_wrapper">
               <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Prénom</th>
                        <th>Adresse</th>
                        <th>Téléphone</th>
                        <th>Sujet</th>
                        <th>Date début</th>
                        <th>Date fin</th>
                        <th>CV</th>
                    </tr>
                    </thead>
                    {% for stagiaire in entities %}
                    <tbody>
                    <tr class="odd gradeX">
                        <td>{{ stagiaire.Nom }}</td>
                        <td>{{ stagiaire.Prenom }}</td>
                        <td>{{ stagiaire.Adresse }}</td>
                        <td>{{ stagiaire.Tel }}</td>
                        <td>{{ stagiaire.sujet }}</td>
                        <td>{{ stagiaire.datedeb|date('d/m/Y') }}</td>
                        <td>{{ stagiaire.datefin|date('d/m/Y') }}</td>
                        <td align="center"><a href="{{ asset(stagiaire.cv.webPath) }}"><i class="fa fa-download"></i></a></td>


                    </tr>
                    </tbody>
                    {% endfor %}
               </table>
           </div>
       </div>
    </div>
    </div>
    {% block panel %}
    {% endblock  %}
{% endblock %}